version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Moscow"
    target-branch: "test"
    open-pull-requests-limit: 12
    versioning-strategy: "increase-if-necessary"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "server"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:
      server-prod-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      server-dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Moscow"
    target-branch: "test"
    open-pull-requests-limit: 12
    versioning-strategy: "increase-if-necessary"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "client"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:
      client-prod-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      client-dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "Europe/Moscow"
    target-branch: "test"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:30"
      timezone: "Europe/Moscow"
    target-branch: "test"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "container"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Europe/Moscow"
    target-branch: "test"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "container"
    commit-message:
      prefix: "chore"
      include: "scope"
